<?php

namespace Cruda;

use PHPUnit\Framework\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-04-08 at 17:05:36.
 */
class BDConexionTest extends TestCase {

    /**
     * @var BDConexion
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BDConexion;
    }

    /**
     * @test
     */
    public function testErrorConexion() {
        $this->assertNull($this->object->connect_error);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
