<?php

namespace Cruda;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-04-08 at 18:13:21.
 */
class ModeloGenericoTest extends TestCase {

    /**
     * @var ModeloGenerico
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        ;
    }

    /**
     * @test
     */
    public function test1_arrayIncompleto() {
        $array1 = array("id" => 1);
        $prueba1 = new ModeloGenerico($array1);
        $this->assertInstanceOf(ModeloGenerico::class, $prueba1);
    }

    /**
     * @test
     */
    public function test2_arrayCompleto() {
        $array2 = array("id" => 1, "nombre" => "Prueba");
        $prueba2 = new ModeloGenerico($array2);
        $this->assertInstanceOf(ModeloGenerico::class, $prueba2);
    }

    /**
     * @expectedException \Exception
     * @expectedExceptionCode 101
     */
    public function test3_arrayNulo() {
        $paramNulo = null;
        $prueba3 = new ModeloGenerico($paramNulo);
    }

    /**
     * @expectedException \Exception
     * @expectedExceptionCode 100
     */
    public function test4_faltaParametro() {
        $prueba4 = new ModeloGenerico();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
