-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 11:03:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuarios` DEFAULT CHARACTER SET utf8 ;
USE `usuarios` ;

-- -----------------------------------------------------
-- Table `usuarios`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `usuarios`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `mail` VARCHAR(250) NULL,
  `whatsaap` VARCHAR(250) NULL,
  `password` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`SISTEMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios`.`SISTEMA` ;

CREATE TABLE IF NOT EXISTS `usuarios`.`SISTEMA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios`.`ROL` ;

CREATE TABLE IF NOT EXISTS `usuarios`.`ROL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `fk_sistema` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ROL_SISTEMA1_idx` (`fk_sistema` ASC) ,
  CONSTRAINT `fk_ROL_SISTEMA1`
    FOREIGN KEY (`fk_sistema`)
    REFERENCES `usuarios`.`SISTEMA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`PERMISO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios`.`PERMISO` ;

CREATE TABLE IF NOT EXISTS `usuarios`.`PERMISO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `fk_sistema` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PERMISO_SISTEMA1_idx` (`fk_sistema` ASC) ,
  CONSTRAINT `fk_PERMISO_SISTEMA1`
    FOREIGN KEY (`fk_sistema`)
    REFERENCES `usuarios`.`SISTEMA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`ROL_PERMISO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios`.`ROL_PERMISO` ;

CREATE TABLE IF NOT EXISTS `usuarios`.`ROL_PERMISO` (
  `fk_rol` INT NOT NULL,
  `fk_permiso` INT NOT NULL,
  PRIMARY KEY (`fk_rol`, `fk_permiso`),
  INDEX `fk_ROL_has_PERMISO_PERMISO1_idx` (`fk_permiso` ASC) ,
  INDEX `fk_ROL_has_PERMISO_ROL_idx` (`fk_rol` ASC) ,
  CONSTRAINT `fk_ROL_PERMISO_ROL`
    FOREIGN KEY (`fk_rol`)
    REFERENCES `usuarios`.`ROL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROL_PERMISO_PERMISO1`
    FOREIGN KEY (`fk_permiso`)
    REFERENCES `usuarios`.`PERMISO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`USUARIO_ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios`.`USUARIO_ROL` ;

CREATE TABLE IF NOT EXISTS `usuarios`.`USUARIO_ROL` (
  `fk_usuario` INT NOT NULL,
  `fk_rol` INT NOT NULL,
  PRIMARY KEY (`fk_usuario`, `fk_rol`),
  INDEX `fk_USUARIO_has_ROL_ROL1_idx` (`fk_rol` ASC) ,
  INDEX `fk_USUARIO_has_ROL_USUARIO1_idx` (`fk_usuario` ASC) ,
  CONSTRAINT `fk_USUARIO_ROL_USUARIO1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `usuarios`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_ROL_ROL1`
    FOREIGN KEY (`fk_rol`)
    REFERENCES `usuarios`.`ROL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `usuarios` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
